# ????
server:
  port: 8181


spring:

  # ?? ????? ?? ????
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

  #???? ??
  mvc:
    view:
      prefix: "resources/templates/"
      suffix: .html
