# ????
server:
  port: 8181


spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

  #???? ??
  mvc:
    view:
      encoding: UTF-8
      cache: false
      prefix: "resources/templates/"
      suffix: .html

  # MYSQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_01
    username: jh950925
    password: rla123

  # JPA
  jap:
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true